apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-micro-services-admin
  labels:
    app: eos-micro-services-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos-micro-services-admin
  template:
    metadata:
      labels:
        app: eos-micro-services-admin
    spec:
      containers:
      - name: eos-micro-services-admin
        image: docker.io/etorrence93/et-micro-admin:1.0
        ports:
        - containerPort: 8090
